sudo: false
language: rust

before_script:
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs --crate cobalt --force --target x86_64-unknown-linux-gnu
  - export PATH="$PATH:/home/travis/.cargo/bin"

script:
  - cobalt build

branches:
  only:
    - staging
    - trying
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master

env:
  global:
    secure: CoyWcelKZrFd9rY+hTPaUU40VcrZ4BvC5yL9xdkci5B+v/mseNo73K16k9ONk9pDMmoqNGx0FqF/le+CBY1NSJtXAPRIJKuZix5VRLd4y3o+QYzySpEie/Afjvny3vaMTb8bb8WkMSwswt0QRTiqgj7Xc2SUFFlkGkv/hmLeMu2Rx8IBiWJy2mhLipaxrDd8tkuUPlOy+sgNNjChLZfh8PexYI6TJlt2uZef2wBp1iM2aQFgH5iH7Gf+CnG3cbEkr+1IdH312+0vCJQl1RdZ8noNVECa/2lYeTPdZlqCbw1jG9CJsaozVYaCx6sa5tdT/UwzqoGq6Go3BvzO3VGzSF454EHhOCSUK08jwE5yG5yxmhg/KfqM0zu6IrXFtrs/9B5toR8D2DtUkP7YvGpp47RByCLteESEpfddyZKMaZafnLEBH6nTXJAhbdKzXrvITB88kCnDL9eFyF+ikPJi0qtEriVg5h1XMNxnu5u0L7dRNcq7388nP0xklGuRYCsypUDCgT+9gOQfK/YfPFVn0SDiQngkCC5XFLKRuSyY5gQd9xAkQw6YRsYx2HSCjN1TWoPS50L/7muNhPeTESwhldzWckcQBvJnOrnPczbRmya5Lx5TG6QgwK7kNPILEdKMh5nmVTk4Db+FjMT2k6/6dWYiq/lNjTg8aPnIrV5DIr8=

notifications:
  email: false
